import { Manrope } from 'next/font/google'
import './globals.css'

const manrope = Manrope({
  subsets: ['latin','cyrillic'],
  weight: ['400', '700']
})

import Navbar from '@/components/Navbar'
  
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Navbar />
        <main className='container '>
          {children}</main>
      </body>
    </html>
  )
}
